### ISSUE TITLE
Enter Certificate, Private Key to URLCredential, that may me do TLSHandshake

### ISSUE THREAD

**Issue by Yolo-Yoda** [apple/swift-certificates#134]
How i can enter Certificate, Private Key to URLCredential?

**Comment by Lukasa** [comment]
You need to convert these types into a `SecKey` and `SecCertificate`, which you can then use to create a `SecIdentity`, which you can then use to create a `URLCredential`. There's no shortcut to doing this other than to serialize the types using `DER.Serializer` and then using `SecKeyCreateWithData` and `SecCertificateCreateWithData`.
