### ISSUE TITLE
SignedAttributes in CMSSignerInfo

### ISSUE THREAD

**Issue by urmat-okonov** [apple/swift-certificates#147]
Is it planned to support SignedAttributes and UnsignedAttributes in [CMSSignerInfo](https://github.com/apple/swift-certificates/blob/main/Sources/X509/CryptographicMessageSyntax/CMSSignerInfo.swift)? Our backend requires SignedAttributes to detect SigningTime for validation.

**Comment by dnadoba** [comment]
It is currently not planned but we are open to contributions. `SignedAttributes` and `UnsignedAttributes` are documented in [RFC 5652 - Section 5.3](https://datatracker.ietf.org/doc/html/rfc5652#section-5.3).
