### ISSUE TITLE
Documentation request: How to create a `Certificate` instance based on `SecCertificateCopyData(:)` DER data?

### ISSUE THREAD

**Issue by tscholze** [apple/swift-certificates#168]
Would it be possible to add a documentation for the following use case:

Reading a DER-`Data` object via `SecCertificateCopyData(:)` from the keychain and transforming it into a `Certificate` instance to have access to the date values of the X501? I checked the ASN1 documentation but I was not able to find an answer.

Thanks!

**Comment by Lukasa** [comment]
Yes, this would be a really good bit of narrative documentation.

The reality is that it's just two steps: take the object from `SecCertificateCopyData`, pass it to the `Certificate(derEncoded:)` constructor. Everything should work well from there. But it'd be very valuable to add a piece of narrative documentation.

Even nicer might be to add a helper extension into the code that can do this directly. Something like:

```swift
#if canImport(Security)
import Security 

extension SecCertificate {
    public init(_ certificate: Certificate) throws {
        // code here
    }
}

extension Certificate {
    public init(_ certificate: SecCertificate) throws {
        // code here
    }
}
#endif
```

That plus tests would be really nice. Are you interested in adding either?

**Comment by tscholze** [comment]
@Lukasa thanks for your response! I put it on my list :).

I already tried your approach:

```swift

import CryptoKit
import X509
import SwiftASN1

// 1. get the SecCertificate
var rawCert: SecCertificate!
SecIdentityCopyCertificate(identity, &rawCert)
         
// 2. pass it to the constructor   
let certificate = Certificate(derData: SecCertificateCopyData(rawCert))

// 3. Causing an error
'CFData' is not convertible to 'String'
```

Using a `as Data` and than a `String(data:encoding)` was not helpful, too. 
I know this is not a support platform, I just want to understand it - so I can contribute (and get my work done). :)

**Comment by Lukasa** [comment]
Not convertible to String is a weird error. Similarly, `derData` is not one of the constructors we offer.

Does this line work? `let certificate = Certificate(derData: SecCertificateCopyData(rawCert) as Data)`

**Comment by Lukasa** [comment]
Oh sorry, this is the right line:

```
let certificate = Certificate(derEncoded: Array(SecCertificateCopyData(rawCert) as Data))
```

**Comment by tscholze** [comment]
@Lukasa awesome! `derData` was an autocompletion, maybe an hiccup because a property was named the same.

Thank you a lot for providing such an amazing lib. :)

**Comment by tscholze** [comment]
I will check if I'm capable of doing the implementation - but sadly not now. :)

**Comment by dm-zharov** [comment]
I'm making [SwiftSecurity](https://github.com/dm-zharov/swift-security) library for type-safe working with native `Security` framework. My library includes storage of `X509.Certificate`. If you want to see, [there is implementation](https://github.com/dm-zharov/swift-security/blob/d58d7b942d88c782abb76d710217c43015bd618c/Sources/SwiftSecurity/CryptoKit/SecCertificateConvertible.swift#L44) of bridging between `SecCertificate` and `X509.Certificate`.

The final code syntax for developers:
```swift
import X509

// Create X.509 Certificate
try certificate = Certificate(derRepresentation: certificateData)

// Get Data
certificate.derRepresentation /* Uses DER.Encoder() */

// Store X.509 Certificate in Keychain
try keychain.store(certificate, query: .certificate(for: "Root CA"))
```

**Comment by Lukasa** [comment]
Very nice! If you wanted to upstream a minimal version of the conversion code into this repo we'd happily accept it.

**Comment by dnadoba** [comment]
Fixed by https://github.com/apple/swift-certificates/pull/182
