### ISSUE TITLE
Information: Test `testCertificateDescription` fails on Mac platform

### ISSUE THREAD

**Issue by tscholze** [apple/swift-certificates#169]
This issue is purely meant as an information, no bug report.

In my attempt to contribute to this repository, I ran all tests `CertificateTests.swift` with "On My Mac" (14.4.1 (23E224)) selected.

Xcode (Version 15.3 (15E204a)) told me, that the test `testCertificateDescription` failed.

If I select an iPad simulator as target, it finishes successful. That's why I think, I execute the tests in an incorrect manner. 

**Assertion message**
```
XCTAssertEqual failed: ("Certificate(version: X509v3, serialNumber: 1:2:3:4:5:6:7:8:9:a, issuer: "CN=Swift Certificate Test CA 1,O=Apple,C=US", subject: "CN=Swift Certificate Test CA 1,O=Apple,C=US", notValidBefore: 2022-08-08 2:26:14 PM +0000, notValidAfter: 2033-08-05 2:26:14 PM +0000, publicKey: P384.PublicKey, signature: ECDSA, extensions: [BasicConstraints(CA=TRUE), KeyUsage(keyCertSign), SubjectKeyIdentifier(4e:51:c6:12:55:3d:95:ba:c3:88:c9:11:6:6f:6e:6c:ff:54:a6:1c)])") is not equal to ("Certificate(version: X509v3, serialNumber: 1:2:3:4:5:6:7:8:9:a, issuer: "CN=Swift Certificate Test CA 1,O=Apple,C=US", subject: "CN=Swift Certificate Test CA 1,O=Apple,C=US", notValidBefore: 2022-08-08 14:26:14 +0000, notValidAfter: 2033-08-05 14:26:14 +0000, publicKey: P384.PublicKey, signature: ECDSA, extensions: [BasicConstraints(CA=TRUE), KeyUsage(keyCertSign), SubjectKeyIdentifier(4e:51:c6:12:55:3d:95:ba:c3:88:c9:11:6:6f:6e:6c:ff:54:a6:1c)])")
```

**Comment by dnadoba** [comment]
The issue is the date format:
```
2022-08-08 2:26:14 PM +0000
```
vs.
```
2022-08-08 14:26:14 +0000
```
I guess this could be because `Date.debugDescription` uses the system settings to do format the date.

**Comment by Lukasa** [comment]
Yeah, I think we should consider using Date objects directly and templating them into the target string.
