### ISSUE TITLE
Using `GeneralName.directoryName` results in a corrupt certificate

### ISSUE THREAD

**Issue by andreasley** [apple/swift-certificates#177]
Commit hash: d93756ba92cde1891de0f433884a7b197bb28d4b

I'm trying to create a `Certificate` that is signed by a (pre-existing, imported) CA certificate.
To make a valid chain, I'm specifying an Authority Key Identifier for the new `Certificate` by passing the CA certificate's issuer as a `DistinguishedName` into a `GeneralName.directoryName`.

The resulting certificate is malformed, which is clearly visible when analyzing it with the following command:

`$ openssl x509 -in /path/to/generated/cert.pem -text -noout`

Actual output (varies with each generation!):
```
        X509v3 extensions:
            X509v3 Authority Key Identifier: 
                0...../CA......|ob...@...%.....
```

Expected output:
```
        X509v3 extensions:
            X509v3 Authority Key Identifier: 
                DirName:/C=Some Country/O=Some Org/CN=CA
```

I suspect the problem could originate in [swift-asn1](https://github.com/apple/swift-asn1) (maybe [here](https://github.com/apple/swift-asn1/blob/7b2855eb0aede67ce062163c729c2d184cc043ab/Sources/SwiftASN1/DER.swift#L865)?).

Minimal reproducible example:
```swift
import Foundation
import X509
import Crypto

let leafPrivateKey = P256.Signing.PrivateKey()

let now = Date()

let issuer = try DistinguishedName {
    CommonName("CA")
    OrganizationName("Some Org")
    CountryName("Some Country")
}

let leafCertificate = try Certificate(
    version: .v3,
    serialNumber: Certificate.SerialNumber(),
    publicKey: Certificate.PublicKey(leafPrivateKey.publicKey),
    notValidBefore: now.addingTimeInterval(-60 * 60 * 24),
    notValidAfter: now.addingTimeInterval(60 * 60 * 24 * 395),
    issuer: .init(),
    subject: .init(),
    signatureAlgorithm: .ecdsaWithSHA512,
    extensions: try Certificate.Extensions {
        AuthorityKeyIdentifier(authorityCertIssuer: [.directoryName(issuer)], authorityCertSerialNumber: Certificate.SerialNumber())
    },
    issuerPrivateKey: Certificate.PrivateKey(leafPrivateKey)
)

if let certFilePemData = try leafCertificate.serializeAsPEM().pemString.data(using: .ascii) {
    let temporaryCertFileURL = URL(string: "/path/to/generated/cert.pem")!
    try certFilePemData.write(to: temporaryCertFileURL)
}
```

**Technical details:**

$ swift --version
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

Operating system: macOS 14.5

$ uname -a
Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64

**Comment by Lukasa** [comment]
Thanks for filing this! You're right that we don't seem to be doing what OpenSSL expects, but I don't think this is a swift-asn1 bug. I think this is an issue in the way we serialize this specific field. I know what we're doing differently, but I'm doing a bit of digging to try to work out _why_ we're doing it differently.

**Comment by Lukasa** [comment]
Ok so I've got this, the issue here is the implicit tagging of general name. I think I have a fix in flight but it's triggering a bit of a weird Swift behaviour, so I'm going to chat with the Swift team quickly to work out how we could work around it.

**Comment by andreasley** [comment]
Did you ever find a possible workaround?
Let me know if there's anything I can help with!

**Comment by erikgadireddi** [comment]
@Lukasa I had simular issue with DistinguishedName when parsing x509 certificate subjectAlternativeNames extension. 
I will prepare minimal example to reproduce the issue, but it seems to me there are some issues when the library expects implicit tagging, but the certificate has explicit tagging of some attributes in the asn1 tree structure.
I will open new issue once I have minimal simple working example where to show it.

**Comment by Lukasa** [comment]
Yeah, so the issue I'm running into here is that we have incorrectly made `GeneralName` `DERImplicitlyTaggable`. It isn't, and can't be, but sadly deprecating the conformance isn't quite enough to get this to do what I want. I'm working through a plan to get this working a bit better.

**Comment by Lukasa** [comment]
Take a look at #188: please feel free to give it a quick try and confirm whether it resolves your issue.

**Comment by andreasley** [comment]
> Take a look at #188: please feel free to give it a quick try and confirm whether it resolves your issue.

That PR **does** resolve the issue on my end. 
The resulting certificate is properly parsed by OpenSSL and various tools on macOS.

Thank you!
