### ISSUE TITLE
GeneralName conformance to CustomStringConvertible seems to be wrong

### ISSUE THREAD

**Issue by erikgadireddi** [apple/swift-certificates#198]
# Reason why it is bad
String(reflecting:) adds extra formatting that is meant for debugging. For example, if the value is a String, String(reflecting:) will wrap it in double quotes ("). This kind of output is intended for debugging purposes, not for user-facing descriptions or parsing.

# Why it makes my use case more complex than it should be
Sometimes I am parsing SubjectAlternativeNames from x509 certificates to UI. The values in SAN are array of General Name. 
General Name could be several objects... 
The additional "" for string values are unnecessary characters to show in the UI, that are not necessary and If I want to extract for example only value from the GeneralName description it is making it too complicated, than it should be.  

# What seems to me the right way?
Use String(describing:) in the code below:
https://github.com/apple/swift-certificates/blob/b1bef483a3de3096446d2b8d9080619bcb6da255/Sources/X509/GeneralName.swift#L110
<img width="751" alt="Screenshot 2024-09-11 at 13 35 49" src="https://github.com/user-attachments/assets/9f79d677-ca62-4764-b145-105062d04b42">

**I will create a PR with changes, if you agree that this make sense to change.**

**Comment by Lukasa** [comment]
I'm afraid I think we believe the current behaviour is correct.
