### ISSUE TITLE
Add `detachedContent: Bool` capability to `CMS.sign` method

### ISSUE THREAD

**Issue by lorenzofiamingo** [apple/swift-certificates#201]
Maybe I'm missing this capability, but could be added `detachedContent: Bool` (like with [`CMSEncoderSetHasDetachedContent`](https://developer.apple.com/documentation/security/cmsencodersethasdetachedcontent(_:_:)) or [`CMSEncodeContent`](https://developer.apple.com/documentation/security/cmsencodecontent(_:_:_:_:_:_:_:_:))) to [`CMS.sign`](https://github.com/apple/swift-certificates/blob/d8799da503be1dd95cb9128478b5c3b22451a4b2/Sources/X509/CryptographicMessageSyntax/CMSOperations.swift#L21) method?
Thank you for this awesome library!

**Comment by Lukasa** [comment]
Hi @lorenzofiamingo, thanks for filing this issue!

What are you looking to achieve? Currently the library _always_ produces detached signatures. Are you looking to add support for producing attached ones?

**Comment by lorenzofiamingo** [comment]
Hi there! Yes, please do produce the attached one. Thanks you very much!

**Comment by Lukasa** [comment]
Ok, fantastic. This is not super high on my priority list so I won't get to it very soon, but I'll mark this as a good first issue for the community, as I'm happy to walk someone through the changes that would have to be made.

**Comment by Lukasa** [comment]
Thanks for stepping in @jonct! Let's discuss the solution there on the diff.
