### ISSUE TITLE
'kSecAttrKeyTypeECDSA' is unavailable in iOS

### ISSUE THREAD

**Issue by peterkaszatrendency** [apple/swift-certificates#202]
I'm getting a build error with the new 1.6 version:
'kSecAttrKeyTypeECDSA' is unavailable in iOS

https://github.com/apple/swift-certificates/blob/d8799da503be1dd95cb9128478b5c3b22451a4b2/Sources/X509/SecKeyWrapper.swift#L122

**Comment by Lukasa** [comment]
Thanks for filing! This looks like some missing API surface in Security framework we need to fill in. 

Are you open to filing a PR that resolves the issue? If not, I can tackle this tomorrow UK time.

**Comment by peterkaszatrendency** [comment]
If I change kSecAttrKeyTypeECDSA (it's deprecated, and it's only on osx) to kSecAttrKeyTypeECSECPrimeRandom, the build is ok. But I can't validate it that the function is working well.
