### ISSUE TITLE
Add support for SecureEnclave.P256.Signing.PrivateKey

### ISSUE THREAD

**Issue by jschlesser** [apple/swift-certificates#51]
In short I would like to be able to use the following code:

`let key = try Certificate.PrivateKey(SecureEnclave.P256.Signing.PrivateKey())` or some variation thereof.

**Comment by Lukasa** [comment]
This is definitely something we can and should enable. I think the patch required to do it should be fairly easy: are you interested in trying to tackle it?

**Comment by jschlesser** [comment]
👋  @Lukasa,
Hmm, if you think it's fine, I'll give it a try.   I'm very new to Swift.   Other than the probably overly ambitious hobby project that I'm working on this would be my first project addition in Swift and first for an Apple platform.  I'm not new to programming, but definitely to programming Swift and for macOS.  On the surface it seems like straight forward additions in the CertificatePrivateKey and CertificatePublicKey extensions.   On the other hand I will need to add CryptoKit as a dependency and I think the SecureEnclave stuff is only available on later versions of some Apple platforms tvOS(15.0+) https://developer.apple.com/documentation/cryptokit/ and not at all on non apple platforms.   Is this going to be testable in Docker?   I don't have any idea about how to do the platform checking etc... nor how to conditionally make binaries for CryptoKit enabled platforms.   I'm willing to give it a shot though if you think it's a good first addition and are willing to coach me through it or you don't think I need to worry about things I'm worrying about.
