### ISSUE TITLE
Generate SSL certificate that is signed by self signed Certificate Authority

### ISSUE THREAD

**Issue by softshipper** [apple/swift-certificates#66]
Hi all, 
I would like to create a SSL certificate and sign it by self signed Certificate Authority.
With OpenSSL I would use the following statement:
```
openssl x509 -req \
    -in server.csr \
    -CA rootCA.crt -CAkey rootCA.key \
    -CAcreateserial -out server.crt \
    -days 365 \
    -sha256 -extfile cert.conf
``` 
Unfortunately, the [Certificate](https://swiftpackageindex.com/apple/swift-certificates/0.3.0/documentation/x509/certificate) struct does not provide parameters to pass the ROOT CA.
I would be very happy if someone could help.

Thanks

**Comment by Lukasa** [comment]
The fields from the root CA that this will add are the issuer name. It will then use the
private key to do the signing. You can use [this initializer](https://swiftpackageindex.com/apple/swift-certificates/0.3.0/documentation/x509/certificate/init(version:serialnumber:publickey:notvalidbefore:notvalidafter:issuer:subject:signaturealgorithm:extensions:issuerprivatekey:)) to achieve the intended result.

**Comment by softshipper** [comment]
Thanks for your answer. I am going to try and let you know. 

Best regards
