### ISSUE TITLE
swift-crypto didn't compile result in linker problem

### ISSUE THREAD

**Issue by S-heep** [apple/swift-certificates#78]
I am using swift-certificate in MacOS project, there is a problem with me .
the detail is 
"
clang: error: no such file or directory: '/Users/xx/Library/Developer/Xcode/DerivedData/xx/Build/Products/Debug/PackageFrameworks/Crypto_17A3B1FFC41E47_PackageProduct.framework/Crypto_17A3B1FFC41E47_PackageProduct'
Command Ld failed with a nonzero exit code
"

**Comment by S-heep** [comment]
Aready remove the derived data folder and rebuild, same error always appeared.

**Comment by Lukasa** [comment]
In this case then I think you'll need to use [Feedback Assistant](https://feedbackassistant.apple.com) or [the Apple Developer Forums](https://developer.apple.com/forums/) to ask for help with Xcode, as I believe this is not an issue with Swift Crypto itself.

**Comment by S-heep** [comment]
Thanks for your advice, I have solved this problem, It is not related to Swift Crypto.
