### ISSUE TITLE
Get data from public key

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [apple/swift-certificates#99]
I'm trying to use this with vapor to build a micro service capable of handling app attestation. Part of that is:
> Create the SHA256 hash of the public key in credCert, and verify that it matches the key identifier from your app.

Problem is the public key exposes no way to do this. It'd be very helpful if `Certificate.PublicKey` would conform to `DataProtocol`, or expose bytes, or something along those lines.

**Comment by dnadoba** [comment]
You can already get the underlying key out of a `Certificate.PublicKey` by trying to initialisers the concrete key types from `CryptoKit` by calling these initlizers: https://github.com/apple/swift-certificates/blob/4a668badd32ed65631dde544dbef9e3c99f98884/Sources/X509/CertificatePublicKey.swift#L243-L305 
just try out all of them and you get access to the underlying bytes in whichever format you want.

What you usually want is to get the bytes in a format similar to `SubjectPublicKeyInfo`:
https://github.com/apple/swift-certificates/blob/4a668badd32ed65631dde544dbef9e3c99f98884/Sources/X509/CertificatePublicKey.swift#L204-L228

We could also think about making `SubjectPublicKeyInfo` public. WDYT @Lukasa?

**Comment by Lukasa** [comment]
I would be open to us exposing a `spkiBytes` field.

**Comment by dnadoba** [comment]
@Tyler-Keith-Thompson would you like to open a PR to add a public property with a bit of documentation to `Certificate/PublicKey`? Something similar to this:
```swift
extension Certificate.PublicKey {
    @inlinable
    public var spkiBytes: ArraySlice<UInt8> {
         SubjectPublicKeyInfo(self).key.bytes
    }
}

**Comment by Tyler-Keith-Thompson** [comment]
Sounds good! I'll get a PR started, thanks!

**Comment by Tyler-Keith-Thompson** [comment]
Wanted to follow-up and confirm that the workaround of trying every key type did the trick:

```swift
// 5. Create the SHA256 hash of the public key in credCert, and verify that it matches the key identifier from your app.
let publicKeyHash = Data(SHA256.hash(data: {
    if let p256 = P256.Signing.PublicKey(credCert.publicKey) {
        return p256.x963Representation
    } else if let p384 = P384.Signing.PublicKey(credCert.publicKey) {
        return p384.x963Representation
    } else if let p521 = P521.Signing.PublicKey(credCert.publicKey) {
        return p521.x963Representation
    } else if let rsa = _RSA.Signing.PublicKey(credCert.publicKey) {
        return rsa.pkcs1DERRepresentation
    } else {
        return Data()
    }
}()))
```

**Comment by dnadoba** [comment]
@Tyler-Keith-Thompson I'm no longer sure if this is the correct way to hash the public key and we may actually want to hash over the full DER representation of `SubjectPublicKeyInfo`. I'm currently trying to find that out.

In the meantime I wanted to ask you upfront if you already tried it out and if so if the hash matched or not?

**Comment by Tyler-Keith-Thompson** [comment]
The hash matched as expected with x963. It did not match with the DER representation.
